// Top-level build file where you can add configuration options common to all sub-projects/modules.
// project root build.gradle
buildscript {
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:2.2.0"
    }
}
plugins {
    alias(libs.plugins.android.application) apply false
}
