plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.example.finalwork'
    compileSdk {
        version = release(36)
    }

    defaultConfig {
        applicationId "com.example.finalwork"
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        ndk {
            abiFilters "arm64-v8a", "armeabi-v7a"
        }
        // 添加推送厂商占位符（可以为空，表示不使用）
        manifestPlaceholders = [
                // 小米推送
                XIAOMI_APPID : "",
                XIAOMI_APPKEY: "",

                // VIVO推送
                VIVO_APPID   : "",
                VIVO_APPKEY  : "",

                // 荣耀推送
                HONOR_APPID  : "",

                // OPPO推送
                OPPO_APPKEY  : "",
                OPPO_APPSECRET: "",

                // 华为推送
                HW_APPID     : "",

                // 魅族推送
                MEIZU_APPID  : "",
                MEIZU_APPKEY : ""
        ]
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    sourceSets {
        main {
            jniLibs.srcDir 'libs'
        }
    }
}

dependencies {
    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    implementation files('libs/BaiduLBS_Android.aar')
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
    implementation 'com.github.bumptech.glide:glide:4.16.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.16.0'
    implementation 'androidx.viewpager2:viewpager2:1.0.0'
    implementation 'com.google.android.material:material:1.11.0'

    implementation fileTree(dir:'libs',includes: ['*.aar'])

    api project(':tuiconversation')
    api project(':tuicontact')
    api project(':tuichat')

    // 集成群接龙插件，从 7.1 版本开始支持
    api "com.tencent.imsdk:tuigroupnote-plugin:8.7.7201"
    // 集成群投票插件，从 7.1 版本开始支持
    api "com.tencent.imsdk:tuipoll-plugin:8.7.7201"
    // 集成会话分组插件，从 7.3 版本开始支持
    api "com.tencent.imsdk:tuiconversationgroup-plugin:8.7.7201"
    // 集成会话标记插件，从 7.3 版本开始支持
    api "com.tencent.imsdk:tuiconversationmark-plugin:8.7.7201"
    // 集成消息推送插件，从 7.6 版本开始支持
    api 'com.tencent.timpush:timpush:8.7.7201'
    // 按需集成对应厂商推送包
    api 'com.tencent.timpush:fcm:8.7.7201'
    api 'com.tencent.timpush:xiaomi:8.7.7201'
    api 'com.tencent.timpush:meizu:8.7.7201'
    api 'com.tencent.timpush:oppo:8.7.7201'
    api 'com.tencent.timpush:vivo:8.7.7201'
    api 'com.tencent.timpush:huawei:8.7.7201'
    api 'com.tencent.timpush:honor:8.7.7201'
    // 百度定位SDK依赖的OkHttp（必须加，版本≥3.12.0）
    implementation 'com.squareup.okhttp3:okhttp:3.14.9'
    // 可选：添加Okio（OkHttp依赖）
    implementation 'com.squareup.okio:okio:1.17.5'
}